site_name: Viral Orthology
site_url: https://viralorthology.github.io/

theme:
  name: readthedocs

nav:
  - Home: index.md

  - Usage:
      - Basic Usage: usage/basic_usage.md
      - Tools Parameters: usage/tool_parameters.md

  - Core Pipeline Workflow:
      - Overview: core_pipeline_workflow/overview.md

  - Enrichment Modules:
      - Overview: enrichment_modules/overview.md
      - Synteny: enrichment_modules/synteny.md
      - Aminoacid composition: enrichment_modules/aminoacid_composition.md
      - Secondary structure: enrichment_modules/secondary_structure.md
      - Tertiary structure: enrichment_modules/tertiary_structure.md
      - HMM profile: enrichment_modules/hmm_profile.md
      - Blastp: enrichment_modules/blastp.md

  - Analysis Modules:
      - Overview: analysis_modules/overview.md
      - Z-score: analysis_modules/zscore.md
      - Kimura 2-p: analysis_modules/kimura.md
      - Protein domains: analysis_modules/protein_domains.md
